# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analyzer.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'analyzer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61nalyzer.proto\x12\x08\x61nalyzer\"0\n\x0b\x46ileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"s\n\x0c\x46ileAnalysis\x12\x12\n\nsize_bytes\x18\x01 \x01(\x03\x12\x17\n\x0f\x63haracter_count\x18\x02 \x01(\x03\x12\x12\n\nword_count\x18\x03 \x01(\x03\x12\x12\n\nline_count\x18\x04 \x01(\x03\x12\x0e\n\x06sha256\x18\x05 \x01(\t2L\n\x0c\x46ileAnalyzer\x12<\n\x0b\x41nalyzeFile\x12\x15.analyzer.FileRequest\x1a\x16.analyzer.FileAnalysisBDZBgithub.com/sedittis/jobforge/services/analyzer-go/proto;analyzerpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analyzer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZBgithub.com/sedittis/jobforge/services/analyzer-go/proto;analyzerpb'
  _globals['_FILEREQUEST']._serialized_start=28
  _globals['_FILEREQUEST']._serialized_end=76
  _globals['_FILEANALYSIS']._serialized_start=78
  _globals['_FILEANALYSIS']._serialized_end=193
  _globals['_FILEANALYZER']._serialized_start=195
  _globals['_FILEANALYZER']._serialized_end=271
# @@protoc_insertion_point(module_scope)
