# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.proto import analyzer_pb2 as analyzer__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in analyzer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FileAnalyzerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeFile = channel.unary_unary(
                '/analyzer.FileAnalyzer/AnalyzeFile',
                request_serializer=analyzer__pb2.FileRequest.SerializeToString,
                response_deserializer=analyzer__pb2.FileAnalysis.FromString,
                _registered_method=True)


class FileAnalyzerServicer:
    """Missing associated documentation comment in .proto file."""

    def AnalyzeFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileAnalyzerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeFile': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeFile,
                    request_deserializer=analyzer__pb2.FileRequest.FromString,
                    response_serializer=analyzer__pb2.FileAnalysis.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analyzer.FileAnalyzer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('analyzer.FileAnalyzer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileAnalyzer:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analyzer.FileAnalyzer/AnalyzeFile',
            analyzer__pb2.FileRequest.SerializeToString,
            analyzer__pb2.FileAnalysis.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
